"""
Django settings for Lifestyle project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-r1litq*+9dg7c5hn+jw=^eabe(3d6y=t=3k+n0rbk^3$q=i-d3"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # created app
    "Blog",
    # installed app
    "ckeditor",
    "ckeditor_uploader",
    "taggit",
    "django_extensions",
    "hitcount",
    "crispy_forms",
    "crispy_bootstrap5",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Lifestyle.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.joinpath("templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Lifestyle.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("NAME"),
        "USER": config("USER"),
        "PASSWORD": config("PASSWORD"),
        "HOST": config("HOST"),
        "PORT": config("PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# static settings

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR/ 'staticfiles')
STATICFILES_DIRS =[
    os.path.join(BASE_DIR , 'static')
]

# media settings
MEDIA_URL ="/media/"
MEDIA_ROOT = os.path.join(BASE_DIR /'media')
CKEDITOR_UPLOAD_PATH = "ckeditor/uploads"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# hitcount settings
HITCOUNT_KEEP_HIT_ACTIVE = { 'days': 7 }
# crispy form
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

# ckeditor
CKEDITOR_ALLOW_NONIMAGE_FILES = False 
CKEDITOR_RESTRICT_BY_DATE = True
CKEDITOR_THUMBNAIL_SIZE = (500, 500)

CKEDITOR_CONFIGS = {
    # 'default': {
    #     'width': '150%',
    #     'toolbar': 'Custom',
    #     # Specify Custom Shit - GPL License -
    #     'toolbar_Custom': [
    #         ['Bold', 'Italic', 'Underline', '-', 'Image', 'Link', 'CodeSnippet', '-', 'NumberedList', 'BulletedList', 'HorizontalRule', '-', 'Undo', 'Redo'],
    #     ], 'extraPlugins': 'codesnippet'
    #     # Remove Dialog Tabs
    #     'removeDialogTabs': 'image:advanced;image:Link',
    # }
}

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        # 'height': 'auto',
        'width': 'auto',
        # 'toolbar_Custom': [
        #     # [ 'Strike',  'Undo', 'Redo'],
        #     ['Styles','Format','Undo', 'Redo','Bold', 'Italic', 'Underline'],
        #     ['TextColor', 'BGColor'],
        #     ['NumberedList', 'BulletedList',  'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
        #     # ['Link', 'Unlink', 'Anchor'],
        #     # ['Image', 'Flash', 'Table', 'HorizontalRule'],
        
        #     # [ 'Source']
        # ]
        # Remove Dialog Tabs
        # 'removeDialogTabs': 'link:advanced;',
        'removeDialogTabs': 'link:advanced;link:upload;link:target;image:advanced;image:Link',
        
        
    }
}