# Generated by Django 4.1.7 on 2023-03-17 04:01

import Blog.validators
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "image",
                    models.ImageField(
                        upload_to="pages/what_we_do",
                        validators=[Blog.validators.validate_file_size],
                        verbose_name="Image",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Work",
                "verbose_name_plural": "Works",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50, verbose_name="Firstname")),
                ("lname", models.CharField(max_length=50, verbose_name="Lastname")),
                ("bio", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ("role", models.CharField(max_length=50, verbose_name="Role")),
                (
                    "profile",
                    models.ImageField(
                        upload_to="user/team/profile",
                        validators=[Blog.validators.validate_file_size],
                        verbose_name="Profile Picture",
                    ),
                ),
                ("twitter", models.URLField(verbose_name="Twitter")),
                ("facebook", models.URLField(verbose_name="Facebook")),
                ("instagram", models.URLField(verbose_name="Instagram")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
    ]
