# Generated by Django 4.1.7 on 2023-03-17 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 3, 17, 5, 45, 35, 320870, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
