# Generated by Django 4.1.7 on 2023-03-29 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Pages", "0005_remove_contact_content_contact_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
