# Generated by Django 4.1.7 on 2023-03-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=50, verbose_name="Firstname"),
                ),
                ("lastname", models.CharField(max_length=50, verbose_name="Lastname")),
                (
                    "tell",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Prefer not to say", "Prefer not to say"),
                        ],
                        max_length=50,
                        verbose_name="Gender",
                    ),
                ),
                ("dob", models.DateTimeField(verbose_name="Date Of Birth")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Location"
                    ),
                ),
                ("bio", models.TextField(verbose_name="Bio")),
                (
                    "profile",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user/profiles",
                        verbose_name="Profile Picture",
                    ),
                ),
                ("twitter", models.URLField(verbose_name="Twitter")),
                ("facebook", models.URLField(verbose_name="Facebook")),
                ("instagram", models.URLField(verbose_name="Instagram")),
                ("website", models.URLField(verbose_name="Website")),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
