# Generated by Django 4.1.7 on 2023-03-10 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
