# Generated by Django 4.1.7 on 2023-03-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0006_alter_profile_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="facebook",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram",
            field=models.URLField(blank=True, null=True, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.URLField(blank=True, null=True, verbose_name="Twitter"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
    ]
