# Generated by Django 4.1.7 on 2023-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0008_alter_profile_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date Of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Firstname"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Prefer not to say", "Prefer not to say"),
                ],
                max_length=50,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Lastname"
            ),
        ),
    ]
