# Generated by Django 4.1.7 on 2023-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0013_profile_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="firstname",
            field=models.CharField(
                default="hey", max_length=50, verbose_name="Firstname"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Prefer not to say", "Prefer not to say"),
                ],
                default="male",
                max_length=50,
                verbose_name="Gender",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="lastname",
            field=models.CharField(
                default="hhh", max_length=50, verbose_name="Lastname"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(
                default="ggh", max_length=50, verbose_name="Location"
            ),
            preserve_default=False,
        ),
    ]
