# Generated by Django 4.1.7 on 2023-04-28 02:35

import Blog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0020_alter_profile_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                null=True,
                upload_to="profiles",
                validators=[
                    Blog.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg", "gif"]
                    ),
                ],
                verbose_name="Profile Picture",
            ),
        ),
    ]
