# Generated by Django 4.1.7 on 2023-03-07 05:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_blog_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Content"
            ),
        ),
    ]
