# Generated by Django 4.1.7 on 2023-03-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_alter_comment_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Is Published"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
