# Generated by Django 4.1.7 on 2023-03-27 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0003_alter_blog_is_published_alter_category_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
