# Generated by Django 4.1.7 on 2023-03-07 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0003_alter_blog_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="reference",
        ),
    ]
