# Generated by Django 4.1.7 on 2023-03-07 06:58

import Blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0004_remove_blog_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/blog",
                validators=[Blog.validators.validate_file_size],
                verbose_name="Photo",
            ),
        ),
    ]
