# Generated by Django 4.1.7 on 2023-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0005_blog_likes_alter_blog_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ("-created",),
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
    ]
