# Generated by Django 4.1.7 on 2023-03-07 07:11

import Blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0005_alter_blog_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                default="dd.pnh",
                upload_to="images/blog",
                validators=[Blog.validators.validate_file_size],
                verbose_name="Photo",
            ),
            preserve_default=False,
        ),
    ]
