# Generated by Django 4.1.7 on 2023-04-19 06:44

import Blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0006_alter_blog_options_alter_blog_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="likes",
        ),
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                default="fff.jpj",
                upload_to="blogs",
                validators=[Blog.validators.validate_file_size],
                verbose_name="Photo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
