# Generated by Django 4.1.7 on 2023-04-19 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0007_remove_blog_likes_alter_blog_photo_blog_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="likes",
        ),
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
