# Generated by Django 4.1.7 on 2023-04-28 02:35

import Blog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0008_remove_blog_likes_blog_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                upload_to="blogs",
                validators=[
                    Blog.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg", "gif"]
                    ),
                ],
                verbose_name="Photo",
            ),
        ),
    ]
